TextExpression : 300
XpathExpression : 300
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Wait1
VariableDescription : 
VariableType : 
VariableTypeNamespace :