TextExpression : 120
XpathExpression : 120
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Wait1
VariableDescription : 
VariableType : 
VariableTypeNamespace :