TextExpression : tracking_var_2
XpathExpression : $tracking_var_2
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Logger2
VariableDescription : 
VariableType : 
VariableTypeNamespace :