TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : City_property_1
VariableDescription : city
VariableType : 
VariableTypeNamespace :