TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Country_property_1
VariableDescription : Country
VariableType : 
VariableTypeNamespace :