TextExpression : message
XpathExpression : "Default"
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Name_property_1
VariableDescription : Name
VariableType : 
VariableTypeNamespace :