TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : State_property_1
VariableDescription : test
VariableType : 
VariableTypeNamespace :