TextExpression : schedule_parameter_1
XpathExpression : $schedule_parameter_1
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Logger3
VariableDescription : 
VariableType : 
VariableTypeNamespace :