TextExpression : 'only for test'
XpathExpression : "only for test"
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Logger1
VariableDescription : 
VariableType : 
VariableTypeNamespace :