TextExpression : 
XpathExpression : 
NamespaceList : xsi=http://www.w3.org/2001/XMLSchema-instance
NumberOfWarnings : 0
NumberOfErrors : 1
ExpressionName : 
VariableName : str
VariableDescription : No description.
VariableType : string
VariableTypeNamespace :