<?xml version = '1.0' encoding = 'UTF-8'?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.oracle.com/cloud/adapter/adwdatabase/ADW_REQUEST/types" xmlns="http://xmlns.oracle.com/cloud/adapter/adwdatabase/ADW_REQUEST/types" elementFormDefault="qualified" attributeFormDefault="qualified">   <xs:element name="ADWInput" type="ADWInput"/>   <xs:complexType name="ADWInput">      <xs:sequence/>   </xs:complexType>   <xs:element name="ADWOutputCollection" type="ADWOutputCollection"/>   <xs:complexType name="ADWOutputCollection">      <xs:sequence>         <xs:element name="ADWOutput" type="ADWOutput" minOccurs="0" maxOccurs="unbounded"/>      </xs:sequence>   </xs:complexType>   <xs:complexType name="ADWOutput">      <xs:sequence>         <xs:element name="SERVICE_NAME" type="xs:string" nillable="true"/>      </xs:sequence>   </xs:complexType></xs:schema>