TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : property_1
VariableDescription : 
VariableType : 
VariableTypeNamespace :