TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : integration_property_7
VariableDescription : test Country
VariableType : 
VariableTypeNamespace :