TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : integration_property_2
VariableDescription : test id
VariableType : 
VariableTypeNamespace :