TextExpression : startTime
XpathExpression : /ics:schedule/ics:startTime
NamespaceList : ics=http://www.oracle.com/2014/03/ics/schedule
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : Logger1
VariableDescription : 
VariableType : 
VariableTypeNamespace :