TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : integration_prop3
VariableDescription : 
VariableType : 
VariableTypeNamespace :