TextExpression : message
XpathExpression : ""
NamespaceList : 
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : integration_prop2
VariableDescription : test2
VariableType : 
VariableTypeNamespace :